### ISSUE TITLE
Error with embed autoload

### ISSUE THREAD

**Issue by aquataller** [cicsolutions/yii2-video-embed-widget#1]
Hi, I found this error:

PHP Warning – yii\base\ErrorException

include_once(/Users/Usr/Trabajos/Web/Desarrollo/Web/Sitio/lib/app/vendor/cics/yii2-video-embed-widget/../../../vendor/embed/embed/Embed/autoloader.php): failed to open stream: No such file or directory
1. in /Users/Usr/Trabajos/Web/Desarrollo/Web/Sitio/lib/app/vendor/cics/yii2-video-embed-widget/VideoEmbed.php at line 22

**Comment by CyanoFresh** [comment]
Same

**Comment by CyanoFresh** [comment]
Found solution: vendor\cics\yii2-video-embed-widget\VideoEmbed.php on line 28 change to
```php
include_once(__DIR__ . '/../../../vendor/embed/embed/src/autoloader.php');
```

**Comment by cicsolutions** [comment]
Thanks for this input.  CyanoFresh, your suggested solution is perfect and has been incorporated in this extension.  Thank you both for identifying and fixing this issue!
